sudo: false

addons:
  apt:
    packages:
      # For test dependencies installation
      - git
      - realpath
      # For the time middleware
      - time

script:
  - make test

branches:
  only:
    - master
