sudo: false

addons:
  apt:
    packages:
      # For test dependencies installation
      - git
      # For the time middleware
      - time

env:
  - VERBOSE=1

script:
  - make test

branches:
  only:
    - master
