sudo: false

addons:
  apt:
    packages:
      # chapecron dependencies
      - time      # For the time middleware
      # Test dependencies
      - git       # For test dependencies installation
      - pcregrep  # For complex pattern matching in tests

env:
  - VERBOSE=1

script:
  - make test

branches:
  only:
    - master
